.. _user-guide_input_model-file_notation:

Notation
========

.. literalinclude:: full-hdf5.inc
  :linenos:
  :lines: 1,2,25-29,50
  :language: text

.. dropdown:: Description

  All names of datasets and groups are lowercase.

  Group's name: "notation".

  * Datasets

    * "double counting" - either 0 or 1.
    * "spin-normalized" - either 0 or 1.
    * "exchange-factor" - one number.
    * "on-site-factor" - one number.
