.. math::
    \mathcal{H}
    =&
    \,C_1
    \sum_{\substack{\mu, \\ \alpha \\ i}}
    J^i(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^i
    +
    C_2
    \sum_{\substack{\mu,\nu, \\ \alpha, \beta, \\ i,j}}
    J^{ij}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    +\\&+
    C_3
    \sum_{\substack{\mu,\nu,\lambda, \\ \alpha,\beta,\gamma, \\ i,j,u}}
    J^{iju}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma})
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    S_{\mu+\lambda,\gamma}^u
    +\\&+
    C_4
    \sum_{\substack{\mu,\nu,\lambda,\rho, \\ \alpha,\beta,\gamma,\varepsilon, \\ i,j,u,v}}
    J^{ijuv}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma}, \boldsymbol{r}_{\rho,\alpha\varepsilon})
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    S_{\mu+\lambda,\gamma}^u
    S_{\mu+\rho,\varepsilon}^v
