.. math::
    \mathcal{H}
    =&
    \,C_1
    \sum_{\substack{\mu, \\ \alpha \\ i}}
    J_1^i(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^i
    +\\&+
    C_{2,1}
    \sum_{\substack{\mu, \\ \alpha, \\ i,j}}
    J_{2,1}^{ij}(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    +\\&+
    C_{2,2}
    \sum_{\substack{\mu,\nu, \\ \alpha, \beta, \\ i,j}}
    J_{2,2}^{ij}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    +\\&+
    C_{3, 1}
    \sum_{\substack{\mu, \\ \alpha, \\ i,j,u}}
    J_{3, 1}^{iju}(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    S_{\mu,\alpha}^u
    +\\&+
    C_{3, 2}
    \sum_{\substack{\mu,\nu, \\ \alpha,\beta, \\ i,j,u}}
    J_{3, 2}^{iju}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    S_{\mu+\nu,\beta}^u
    +\\&+
    C_{3, 3}
    \sum_{\substack{\mu,\nu,\lambda, \\ \alpha,\beta,\gamma, \\ i,j,u}}
    J_{3, 3}^{iju}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma})
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    S_{\mu+\lambda,\gamma}^u
    +\\&+
    C_{4, 1}
    \sum_{\substack{\mu, \\ \alpha, \\ i,j,u,v}}
    J_{4, 1}^{ijuv}(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    S_{\mu,\alpha}^u
    S_{\mu,\alpha}^v
    +\\&+
    C_{4, 2, 1}
    \sum_{\substack{\mu,\nu, \\ \alpha,\beta, \\ i,j,u,v}}
    J_{4, 2, 1}^{ijuv}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    S_{\mu,\alpha}^u
    S_{\mu+\nu,\beta}^v
    +\\&+
    C_{4, 2, 2}
    \sum_{\substack{\mu,\nu, \\ \alpha,\beta, \\ i,j,u,v}}
    J_{4, 2, 2}^{ijuv}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    S_{\mu+\nu,\beta}^u
    S_{\mu+\nu,\beta}^v
    +\\&+
    C_{4, 3}
    \sum_{\substack{\mu,\nu,\lambda, \\ \alpha,\beta,\gamma, \\ i,j,u,v}}
    J_{4, 3}^{ijuv}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma})
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    S_{\mu+\nu,\beta}^u
    S_{\mu+\lambda,\gamma}^v
    +\\&+
    C_{4, 4}
    \sum_{\substack{\mu,\nu,\lambda,\rho, \\ \alpha,\beta,\gamma,\varepsilon, \\ i,j,u,v}}
    J_{4, 4}^{ijuv}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma}, \boldsymbol{r}_{\rho,\alpha\varepsilon})
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    S_{\mu+\lambda,\gamma}^u
    S_{\mu+\rho,\varepsilon}^v
