.. math::
    \mathcal{H}
    =&
    \,C_1
    \sum_{\substack{\mu, \\ \alpha \\ k}}
    J^k(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^k
    +
    C_2
    \sum_{\substack{\mu,\nu, \\ \alpha, \beta, \\ k,l}}
    J^{kl}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^k
    S_{\mu+\nu,\beta}^l
    +\\&+
    C_4
    \sum_{\substack{\mu,\nu,\lambda,\rho, \\ \alpha,\beta,\gamma,\varepsilon, \\ k,l,i,j}}
    J^{klij}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma}, \boldsymbol{r}_{\rho,\alpha\varepsilon})
    S_{\mu,\alpha}^k
    S_{\mu+\nu,\beta}^l
    S_{\mu+\lambda,\gamma}^i
    S_{\mu+\rho,\varepsilon}^j
