.. math::
    \mathcal{H}
    =&
    \,C_1
    \sum_{\substack{\mu, \\ \alpha \\ k}}
    J_1^k(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^k
    +\\&+
    C_{2,1}
    \sum_{\substack{\mu, \\ \alpha, \\ k,l}}
    J_{2,1}^{kl}(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    +\\&+
    C_{2,2}
    \sum_{\substack{\mu,\nu, \\ \alpha, \beta, \\ k,l}}
    J_{2,2}^{kl}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^k
    S_{\mu+\nu,\beta}^l
    +\\&+
    C_{3, 1}
    \sum_{\substack{\mu, \\ \alpha, \\ k,l,i}}
    J_{3, 1}^{kli}(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    S_{\mu,\alpha}^i
    +\\&+
    C_{3, 2}
    \sum_{\substack{\mu,\nu, \\ \alpha,\beta, \\ k,l,i}}
    J_{3, 2}^{kli}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    S_{\mu+\nu,\beta}^i
    +\\&+
    C_{3, 3}
    \sum_{\substack{\mu,\nu,\lambda, \\ \alpha,\beta,\gamma, \\ k,l,i}}
    J_{3, 3}^{klij}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma})
    S_{\mu,\alpha}^k
    S_{\mu+\nu,\beta}^l
    S_{\mu+\lambda,\gamma}^i
    +\\&+
    C_{4, 1}
    \sum_{\substack{\mu, \\ \alpha, \\ k,l,i,j}}
    J_{4, 1}^{klij}(\boldsymbol{r}_{\alpha})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    S_{\mu,\alpha}^i
    S_{\mu,\alpha}^j
    +\\&+
    C_{4, 2, 1}
    \sum_{\substack{\mu,\nu, \\ \alpha,\beta, \\ k,l,i,j}}
    J_{4, 2, 1}^{klij}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    S_{\mu,\alpha}^i
    S_{\mu+\nu,\beta}^j
    +\\&+
    C_{4, 2, 2}
    \sum_{\substack{\mu,\nu, \\ \alpha,\beta, \\ k,l,i,j}}
    J_{4, 2, 2}^{klij}(\boldsymbol{r}_{\nu,\alpha\beta})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    S_{\mu+\nu,\beta}^i
    S_{\mu+\nu,\beta}^j
    +\\&+
    C_{4, 3}
    \sum_{\substack{\mu,\nu,\lambda, \\ \alpha,\beta,\gamma, \\ k,l,i,j}}
    J_{4, 3}^{klij}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma})
    S_{\mu,\alpha}^k
    S_{\mu,\alpha}^l
    S_{\mu+\nu,\beta}^i
    S_{\mu+\lambda,\gamma}^j
    +\\&+
    C_{4, 4}
    \sum_{\substack{\mu,\nu,\lambda,\rho, \\ \alpha,\beta,\gamma,\varepsilon, \\ k,l,i,j}}
    J_{4, 4}^{klij}(\boldsymbol{r}_{\nu,\alpha\beta}, \boldsymbol{r}_{\lambda,\alpha\gamma}, \boldsymbol{r}_{\rho,\alpha\varepsilon})
    S_{\mu,\alpha}^k
    S_{\mu+\nu,\beta}^l
    S_{\mu+\lambda,\gamma}^i
    S_{\mu+\rho,\varepsilon}^j
