spinham/
├─── ...
├─── cell/
│    ├──> units
│    ├──> scale
│    ├──> a1
│    ├──> a2
│    └──> a3
├─── atoms/
│    ├──> units
│    ├─── 1/
│    │    ├──> name
│    │    ├──> position
│    │    ├──> spin
│    │    └──> g-factor
│    ├─── ...
│    └─── n/
│         ├──> name
│         ├──> position
│         ├──> spin
│         └──> g-factor
├─── notation/
│    ├──> double-counting
│    ├──> spin-normalized
│    ├──> exchange-factor
│    └──> on-site-factor
├─── ground-state/
│    ├──> units
│    ├──> spiral-vector
│    └──> cone-axis
├─── exchange/
│    ├──> units
│    └─── parameters/
│         ├─── 1/
│         │    ├──> atom-1
│         │    ├──> atom-2
│         │    ├──> ijk
│         │    └──> matrix
│         ├─── ...
│         └─── n/
│              ├──> atom-1
│              ├──> atom-2
│              ├──> ijk
│              └──> matrix
├─── on-site/
│    ├──> units
│    └─── parameters/
│         ├─── 1/
│         │    ├──> atom
│         │    └──> matrix
│         ├─── ...
│         └─── n/
│               ├──> atom
│               └──> matrix
└─── ...
