Classical vectors are denoted using Dirac's notation and small letters.
Vector coordinates in a given basis are arranged in column form,
and its placeholder is denoted by a bold letter, where a left super-index
indicates the basis used. For example, a vector :math:`\ket{r}` has
components

.. math::
  ^z\boldsymbol{r}=\begin{pmatrix}r^x\\r^y\\r^z\end{pmatrix}

in the cartesian reference frame :math:`(\,x\,y\,z\,)`. Notice that
the expression :math:`\boldsymbol{r}` is ambiguous as it does not
indicate the basis.
The modulus of a vector is typed with the same, unbolded, letter. So the modulus of
vector :math:`\boldsymbol{r}`  is just :math:`r`.
Unit vectors are denoted by a hat. An example is

.. math::
  ^z\boldsymbol{\hat{r}} = \dfrac{^z\boldsymbol{r}}{r},

An exception to the small-lettering rule concerns classical spin vectors. These are denoted
by capital bold letters :math:`\boldsymbol{S}` to conform with the usual notation.

See :ref:`user-guide_methods_bra-ket` for the introduction remarks.
