We use two interchageable and fully equivalent notations for the exchange tensor:

.. math::
  \boldsymbol{J}_{ij}(\boldsymbol{d}_{ij})
  =
  \boldsymbol{J}_{\boldsymbol{d}ij}

Note, that the explicit dependency on :math:`\boldsymbol{d}_{ij}` can not be just
dropped, because for each pair :math:`ij` there is not one, but rather a set of several
distance vectors :math:`\boldsymbol{d}_{ij}`, therefore, the exchange tensor is a
function of the pair index :math:`ij` and the distance vector
:math:`\boldsymbol{d}_{ij}`.

For the matrix elements and the decomposition into the symmetric/antysymmetric
parts we use the same notation as for the exchange tensor. For example:

.. math::
  J^I_{ij}(\boldsymbol{d}_{ij})
  =
  J^I_{\boldsymbol{d}ij}

  J^{uv}_{ij}(\boldsymbol{d}_{ij})
  =
  J^{uv}_{\boldsymbol{d}ij}

  S^{uv}_{ij}(\boldsymbol{d}_{ij})
  =
  S^{uv}_{\boldsymbol{d}ij}

  D^{n}_{ij}(\boldsymbol{d}_{ij})
  =
  D^{n}_{\boldsymbol{d}ij}
