Operators are denoted by a bolded capital letter. Matrices are
denoted by a bolded capital letter carrying a left super-script
:math:`^z`, or :math:`^n`, or :math:`^f`.
The left super-index indicates that the matrix elements are
referred to the corresponding basis. An example is the exchange
tensor between two arbitrary sites
:math:`i` and :math:`j` written in the :math:`(x,\,y,\,z)`
reference frame, that is
denoted by :math:`^z\boldsymbol{J}_{ij}`. Its matrix elements
:math:`(\,\alpha,\,\beta\,)`
are denoted as :math:`^zJ_{ij}^{\alpha \beta}`.
