A matrix is denoted with a bold symbol. A super-script :math:`^z`, or :math:`^n`, or :math:`^f`
attached to it indicates that its matrix elements are referred to the corresponding
reference frame. An example is the exchange tensor between two arbitrary sites
:math:`i` and :math:`j` written in the :math:`(x,\,y,\,z)` reference frame, that is
denoted by :math:`\boldsymbol{J}_{ij}^z`. Its matrix elements :math:`(\,\alpha,\,\beta\,)`
are denoted as :math:`J_{ij}^{z, \alpha \beta}`.
