The notation for the different operators appearing in this documentation is

* The Hamiltonian operator is denoted by :math:`{\cal H}`

#* Magnopy's spin notation does not distinguish between classical or quantum spins.
#  These are understood by their context.

* Spin operator vector components are written as :math:`{\cal S}^\alpha`

* Vectors spin operators are denoted by

  .. math::
    \boldsymbol{\cal S}
    =
    ({\cal S}^x,{\cal S}^y,{\cal S}^z)^{\dagger}
    =
    \begin{pmatrix}
      {\cal S}^x \\
      {\cal S}^y \\
      {\cal S}^z
    \end{pmatrix}

* Boson operators with quantum number :math:`n` are written as :math:`a_n` or :math:`b_n`.

* Boson operators are eventually collected into vector boson operators, that are denoted by

  .. math::
    \boldsymbol{\cal A}
    =
    (a_1,a_2,\dots)^{\dagger}
    =
    \begin{pmatrix}
      a_1 \\
      a_2 \\
      \vdots
    \end{pmatrix}

    \boldsymbol{\cal B}
    =
    (b_1,b_2,\dots)^{\dagger}
    =
    \begin{pmatrix}
      b_1 \\
      b_2 \\
      \vdots
    \end{pmatrix}
