The terms "reference frame" = "coordinate system" = "basis".

This documentation uses three reference frames. The first is the conventional cartesian frame
":math:`(x\,y\,z)=\ket{x\,y\,z}`", that is spanned by the unit vectors
:math:`\{\boldsymbol{\hat{x}}`, :math:`\boldsymbol{\hat{y}}`, :math:`\boldsymbol{\hat{z}}\}`.
The second is a global rotated frame that defines the cone axis :math:`\boldsymbol{\hat{n}}`;
this is denoted by ":math:`(u\,v\,n)=\ket{u\,v\,n}`" and is spanned by the set of orthogonal
unit vectors :math:`\{\boldsymbol{\hat{u}}`, :math:`\boldsymbol{\hat{v}}`,
:math:`\boldsymbol{\hat{n}}\}`. The third is the local rotated reference frame defining
each spin :math:`\boldsymbol{\hat{S}}_i= S_i\,\boldsymbol{\hat{f}}_i`; this is
denoted by ":math:`(p_i\,t_i\,f_i)=\ket{p_i\,t_i\,f_i}`" and spanned at each site :math:`i`
by the set of orthogonal unit vectors :math:`\{\boldsymbol{\hat{p}}_i`,
:math:`\boldsymbol{\hat{t}}_i`, :math:`\boldsymbol{\hat{f}}_i\}`.
