The terms "reference frame" = "coordinate system" = "basis".

This documentation uses the conventional cartesian frame ":math:`(x\,y\,z)=\ket{x\,y\,z}`"
that is spanned by the unit vectors
:math:`\{\boldsymbol{\hat{x}}`, :math:`\boldsymbol{\hat{y}}`, :math:`\boldsymbol{\hat{z}}\}`
and a rotated frame denoted by
":math:`(u\,v\,n)=\ket{u\,v\,n}`" that is spanned by the unit vectors
:math:`\{\boldsymbol{\hat{u}}`, :math:`\boldsymbol{\hat{v}}`, :math:`\boldsymbol{\hat{n}}\}`.
Whithin this frame all unit vectors are collinear to :math:`\boldsymbol{\hat{n}}`.
