Rotation matrices are denoted by a bold capital :math:`\boldsymbol{R}` letter, whose subindex identifies
the  unit vector defining the rotation axis and whose argument indicates the rotation angle. As an example

.. math::
  \boldsymbol{R_n}(\theta)= e^{\theta\,\boldsymbol{n}} \,\times

corresponds to a rotation by an angle :math:`\theta` about an axis defined by the unit
vector :math:`\boldsymbol{\hat{n}}`.
