Rotation operators are denoted by a bold capital :math:`\boldsymbol{R}` letter. The letter carries a subindex
that identifies the  unit vector defining the rotation axis
and an argument that indicates the rotation angle.
For example

.. math::
  \boldsymbol{R_\ket{n}}(\theta)= e^{\theta\,\ket{n} \,\times}

performs a rotation of angle :math:`\theta` about the vector
:math:`\ket{n}`.
The corresponding rotation matrix in the :math:`(\,x\,y\,z\,)`
basis is

.. math::
  ^z\boldsymbol{R_n}(\theta)= e^{\theta\,^z\boldsymbol{n} \,\times}
