Every matrix or vector (classical or vector operator) symbol is written in the
:ref:`(uvn) reference frame <user-guide_methods_uvn>`. If the bold superscript appears ":math:`\boldsymbol{^s}`"
in the vector character (i.e :math:`\boldsymbol{S_{mi}^s}`) or matrix symbol
(i.e. :math:`\boldsymbol{R_m^s}(q)`) it means that corresponding quantity is
written in a :ref:`spherical reference frame <user-guide_methods_spherical-rf>`.
Note, that in the coordinate representation the subscripts of the vector/matrix
components indicate the reference frame.
