Classical vectors are denoted by bold small letters.
Their coordinates are written in column form. An example is

.. math::
  \boldsymbol{r} = (r^x, r^y, r^z)^T= \begin{pmatrix} r^x\\r^y\\r^z\end{pmatrix}

An exception to the rule above concerns classical spin vectors. These are denoted
by capital bold letters :math:`\boldsymbol{S}` to conform with the usual notation.

The modulus of a vector is typed with the same, unbolded, letter. So the modulus of vector :math:`\boldsymbol{r}`  is just :math:`r`.
