.. math::
  {\cal H}
  &=
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d}_{ij}, i, j}
  (\boldsymbol{\cal S}_{mi}^{F,s})^{\dagger}\,
  (\boldsymbol{R}_i^s)^\dagger\, (\boldsymbol{R}_m^s)^{\dagger}\,
  \boldsymbol{J}_{\boldsymbol{d}ij}^s\,
  \boldsymbol{R}_{m+d_{ij}}^s\, \boldsymbol{R}_j^s\,
  \boldsymbol{\cal S}_{m+d_{ij},j}^{F,s}
  \\&+
  \mu_B\, (\boldsymbol{h}^s)^{\dagger}\,
  \sum_{m,i}\, g_i\, \boldsymbol{R}_m^s\, \boldsymbol{R}_i^s\, \boldsymbol{\cal S}_{mi}^{F,s}
