.. math::
  {\cal H}^{Cubic}
  &=-
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
  \Biggl[
    S_i^{1/2}
    \left(
      \boldsymbol{\tilde{J}}_{dij}^{f,+0}\,\,a_{mi}\,n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,-0}\,a_{mi}^{\dagger}\,n_{m+d_{ij},j}
    \right)
    \\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}
    +S_j^{1/2}
    \left(
      \boldsymbol{\tilde{J}}_{dij}^{f,0+}\, n_{mi}\,a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}}_{mij}^{f,0-}\, n_{mi}\,a_{m+d_{ij},j}
    \right)
    +\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}-
    \dfrac{S_i}{4\,S_j^{1/2}}\,
    \left(
      \boldsymbol{\tilde{J}}_{dij}^{f,0+}\, a_{m+d_{ij},j}^{\dagger}\, n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,0-}\, n_{m+d_{ij},j}\, a_{m+d_{ij},j}
    \right)
    +\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}-
    \dfrac{S_j}{4\,S_i^{1/2}}\,
    \left(
      \boldsymbol{\tilde{J}}_{dij}^{f,+0}\, n_{mi}\, a_{mi}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,-0}\, a_{mi}^{\dagger}\, n_{mi}
    \right)
  \Biggr]
  -\\&-
  \mu_B \, ^{sf}\boldsymbol{h}^{\dagger}\,
  \sum_{m,i}\, \dfrac{g_i}{4\,S_i^{1/2}}\,
  ^{sf}\boldsymbol{R_m}\,
  \left(\,
    ^{sf}\boldsymbol{\hat{f}^+}_i\,
    a_{mi}^{\dagger}\, n_{mi}
    \,+\,
    ^{sf}\boldsymbol{\hat{f}^-}_i\,
    n_{mi}\, a_{mi}
  \right)
