.. math::
  \boldsymbol{\cal S^s}
  =
  \begin{pmatrix}
    \frac{1}{\sqrt{2}}{\cal S}^- \\
    \frac{1}{\sqrt{2}}{\cal S}^+ \\
    {\cal S}^n \end{pmatrix}
  =
  \begin{pmatrix}
    \frac{1}{\sqrt{2}}\,\left({\cal S}^u - i\,{\cal S}^v\right) \\ \frac{1}{\sqrt{2}}\,\left({\cal S}^u + i\,{\cal S}^v\right) \\
    {\cal S}^n\end{pmatrix}
  =
  \begin{pmatrix}
    \sqrt{S} \,\, a^{\dagger} \,\,\sqrt{1 - \dfrac{a^{\dagger}a}{2S}} \\
    \sqrt{S}\,\,\sqrt{1 - \dfrac{a^{\dagger}a}{2S}}\,\,a \\
    S\,\,(1 - \dfrac{a^{\dagger}\,a}{S})
  \end{pmatrix}
