.. math::
  \boldsymbol{\hat{p}}^s_i
  =
  \dfrac{1}{2}
  \begin{pmatrix}
    1 + \cos\theta_i                  \\
    (\cos\theta_i - 1)\, e^{2i\phi_i} \\
    -\sqrt{2}\, \sin\theta_i\, e^{i\phi_i}
  \end{pmatrix}
  \quad
  \boldsymbol{\hat{t}}^s_i
  =
  \dfrac{1}{2}
  \begin{pmatrix}
    (\cos\theta_i-1)\, e^{-2i\phi_i} \\
    1 + \cos\theta_i                 \\
    -\sqrt{2}\, \sin\theta_i\, e^{-i\phi_i}
  \end{pmatrix}
  \quad
  \boldsymbol{\hat{f}}^s_i
  =
  \dfrac{1}{2}
  \begin{pmatrix}
    \sqrt{2}\, \sin\theta_i\, e^{-i\phi_i}  \\
    \sqrt{2}\, \sin\theta_i\, e^{i\phi_i}   \\
    2\cos\theta_i
  \end{pmatrix}
