.. math::
  \begin{pmatrix}
    J_{\boldsymbol{d}ij}^{++} & J_{\boldsymbol{d}ij}^{+-} & J_{\boldsymbol{d}ij}^{+n} \\
    J_{\boldsymbol{d}ij}^{-+} & J_{\boldsymbol{d}ij}^{--} & J_{\boldsymbol{d}ij}^{-n} \\
    J_{\boldsymbol{d}ij}^{n+} & J_{\boldsymbol{d}ij}^{n-} & J_{\boldsymbol{d}ij}^{nn} \\
  \end{pmatrix}
  =
  \begin{pmatrix}
    J_{\boldsymbol{d}ij}^{++}     & J_{\boldsymbol{d}ij}^{+-}     & J_{\boldsymbol{d}ij}^{+n}     \\
    (J_{\boldsymbol{d}ij}^{+-})^* & (J_{\boldsymbol{d}ij}^{++})^* & (J_{\boldsymbol{d}ij}^{+n})^* \\
    J_{\boldsymbol{d}ij}^{n+}     & (J_{\boldsymbol{d}ij}^{n+})^* & J_{\boldsymbol{d}ij}^{nn}     \\
  \end{pmatrix}

.. math::
  \begin{pmatrix}
    J_{\boldsymbol{d}ij}^{++} & J_{\boldsymbol{d}ij}^{+-} & J_{\boldsymbol{d}ij}^{+n} \\
    J_{\boldsymbol{d}ij}^{-+} & J_{\boldsymbol{d}ij}^{--} & J_{\boldsymbol{d}ij}^{-n} \\
    J_{\boldsymbol{d}ij}^{n+} & J_{\boldsymbol{d}ij}^{n-} & J_{\boldsymbol{d}ij}^{nn} \\
  \end{pmatrix}
  =
  \begin{pmatrix}
    (J_{\boldsymbol{d}ji}^{++})^* & (J_{\boldsymbol{d}ji}^{-+})^* & (J_{\boldsymbol{d}ji}^{n+})^* \\
    (J_{\boldsymbol{d}ji}^{+-})^* & (J_{\boldsymbol{d}ji}^{--})^* & (J_{\boldsymbol{d}ji}^{n-})^* \\
    (J_{\boldsymbol{d}ji}^{+n})^* & (J_{\boldsymbol{d}ji}^{-n})^* & (J_{\boldsymbol{d}ji}^{nn})^* \\
  \end{pmatrix}
