.. math::
  \boldsymbol{J_{\boldsymbol{d}ij}}^s
  &=
  \boldsymbol{T}^\dagger\, \boldsymbol{J_{\boldsymbol{d}ij}}\, \boldsymbol{T}\,
  =
  \begin{pmatrix}
    J_{\boldsymbol{d}ij}^{++} & J_{\boldsymbol{d}ij}^{+-} & J_{\boldsymbol{d}ij}^{+n} \\
    J_{\boldsymbol{d}ij}^{-+} & J_{\boldsymbol{d}ij}^{--} & J_{\boldsymbol{d}ij}^{-n} \\
    J_{\boldsymbol{d}ij}^{n+} & J_{\boldsymbol{d}ij}^{n-} & J_{\boldsymbol{d}ij}^{nn} \\
  \end{pmatrix}
  =\\=&
  \begin{pmatrix}
      J^{I}_{\boldsymbol{d}ij}
      +
      \dfrac{S_{\boldsymbol{d}ij}^{uu} + S_{\boldsymbol{d}ij}^{vv}}{2}
      +
      iD_{\boldsymbol{d}ij}^n
    &
      \dfrac{S_{\boldsymbol{d}ij}^{uu} - S_{\boldsymbol{d}ij}^{vv}}{2} - iS_{\boldsymbol{d}ij}^{uv}
    &
      \dfrac{S_{\boldsymbol{d}ij}^{un} - iS_{\boldsymbol{d}ij}^{vn}}{\sqrt{2}}
      -
      \dfrac{D_{\boldsymbol{d}ij}^v + iD_{\boldsymbol{d}ij}^u}{\sqrt{2}}
    \\
      \dfrac{S_{\boldsymbol{d}ij}^{uu} - S_{\boldsymbol{d}ij}^{vv}}{2} + iS_{\boldsymbol{d}ij}^{uv}
    &
      J^{I}_{\boldsymbol{d}ij}
      +
      \dfrac{S_{\boldsymbol{d}ij}^{uu} + S_{\boldsymbol{d}ij}^{vv}}{2}
      -
      iD_{\boldsymbol{d}ij}^n
    &
      \dfrac{S_{\boldsymbol{d}ij}^{un} + iS_{\boldsymbol{d}ij}^{vn}}{\sqrt{2}}
      -
      \dfrac{D_{\boldsymbol{d}ij}^v - iD_{\boldsymbol{d}ij}^u}{\sqrt{2}}
    \\
      \dfrac{S_{\boldsymbol{d}ij}^{un} + iS_{\boldsymbol{d}ij}^{vn}}{\sqrt{2}}
      +
      \dfrac{D_{\boldsymbol{d}ij}^v - iD_{\boldsymbol{d}ij}^u}{\sqrt{2}}
    &
      \dfrac{S_{\boldsymbol{d}ij}^{un} - iS_{\boldsymbol{d}ij}^{vn}}{\sqrt{2}}
      +
      \dfrac{D_{\boldsymbol{d}ij}^v + iD_{\boldsymbol{d}ij}^u}{\sqrt{2}}
    &
      J^{I}_{\boldsymbol{d}ij} + S_{\boldsymbol{d}ij}^{nn}
    \\
  \end{pmatrix}
