.. math::
  \sum_m
  (\boldsymbol{R_m^s})^{\dagger}(\boldsymbol{q})
  \boldsymbol{J_{ij}^s}(\boldsymbol{d_{ij}})
  \boldsymbol{R_{m+d_{ij}}^s}(\boldsymbol{q})
  =
  M
  \begin{pmatrix}
    e^{-i\boldsymbol{q}\boldsymbol{d_{ij}}} J_{ij}^{++}                                   &
    e^{i\boldsymbol{q}\boldsymbol{d_{ij}}}\delta_{\boldsymbol{q},\frac{\boldsymbol{G}}{2}} J_{ij}^{+-}  &
    \delta_{\boldsymbol{q},\boldsymbol{G}}\cdot J_{ij}^{+n}                          \\
    e^{-i\boldsymbol{q}\boldsymbol{d_{ij}}}\delta_{\boldsymbol{q},\frac{\boldsymbol{G}}{2}} J_{ij}^{-+} &
    e^{i\boldsymbol{q}\boldsymbol{d_{ij}}} J_{ij}^{--}                                    &
    \delta_{\boldsymbol{q},\boldsymbol{G}}\cdot J_{ij}^{-n}                          \\
    e^{-i\boldsymbol{q}\boldsymbol{d_{ij}}}\delta_{\boldsymbol{q},\boldsymbol{G}}\cdot J_{ij}^{n+}      &
    e^{i\boldsymbol{q}\boldsymbol{d_{ij}}}\delta_{\boldsymbol{q},\boldsymbol{G}}\cdot J_{ij}^{n-}       &
    J_{ij}^{nn}                                                        \\
  \end{pmatrix}
