.. math::
  H
  =
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i\ne j\vert_{\boldsymbol{d_{ij}} = \boldsymbol{0}}}
  \boldsymbol{S_{mi}}^{\dagger}\,
  \boldsymbol{J_{ij}}(\boldsymbol{d_{ij}})\,
  \boldsymbol{S_{m+d_{ij},j}}\,
  + \,\sum_{m,i}\,
  \boldsymbol{S_{mi}}^{\dagger}\,
  \boldsymbol{A_i}\,
  \boldsymbol{S_{mi}}\,
  +\,
  \mu_B\,\boldsymbol{h}^{\dagger}\,
  \sum_{m,i}\, g_i\, \boldsymbol{S_{mi}}
