.. math::
  H
  =
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d}_{ij}, i\ne j\vert_{\boldsymbol{d}_{ij}} = \boldsymbol{0}}
  \,^z\boldsymbol{S}_{mi}^\dagger\,
  ^z\boldsymbol{J}_{\boldsymbol{d}ij}\,
  ^z\boldsymbol{S}_{m+d_{ij},j}\,
  + \,\sum_{m,i}\,
  ^z\boldsymbol{S}_{mi}^\dagger\,
  ^z\boldsymbol{A}_i\,
  ^z\boldsymbol{S}_{mi}\,
  +\,
  \mu_B\,^z\boldsymbol{h}^\dagger\,
  \sum_{m,i}\, g_i\, ^z\boldsymbol{S}_{mi}
