.. math::
  {\cal H}
  =
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
  (\boldsymbol{{\cal S}_{mi}^F})^{\dagger}\,
  \boldsymbol{R_i}^\dagger\,\boldsymbol{R_m}^{\dagger}\,
  \boldsymbol{J_{ij}}(\boldsymbol{d_{ij}})\,
  \boldsymbol{R_{m+d_{ij}}}\,\boldsymbol{R_j}\,
  \boldsymbol{{\cal S}_{m+d_{ij},j}^F}
  +
  \mu_B\,\boldsymbol{h}^{\dagger}\,
  \sum_{m,i}\,g_i\,\boldsymbol{R_m}\,\boldsymbol{R_i}\,\boldsymbol{{\cal S}_{mi}^F}
