.. math::
  {\cal H}^{Biquadratic}
  &=
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
  \Biggl[
    \boldsymbol{\tilde{J}}_{dij}^{f,00}\, n_{mi}\, n_{m+d_{ij},j}
    \\&-
    \dfrac{S_i^{1/2}}{4\,S_j^{1/2}}\,
    \Bigl(
      \boldsymbol{\tilde{J}}_{dij}^{f,++}\,
      a_{mi}\, a_{m+d_{ij},j}^{\dagger}\, n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,+-}\,
      a_{mi}\, n_{m+d_{ij},j}\, a_{m+d_{ij},j}\,
      +\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}+
      \boldsymbol{\tilde{J}}_{dij}^{f,-+}\,
      a_{mi}^{\dagger}\, a_{m+d_{ij},j}^{\dagger}\, n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,--}\,
      a_{mi}^{\dagger}\, n_{m+d_{ij},j}\, a_{m+d_{ij},j}\,
    \Bigr)
    \\
    &-
    \dfrac{S_j^{1/2}}{4\,S_i^{1/2}}\,
    \Bigl(
      \boldsymbol{\tilde{J}}_{dij}^{f,++}\,
      n_{mi}\, a_{mi}\, a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,-+}\,
      a_{mi}^{\dagger}\, n_{mi}\, a_{m+d_{ij},j}^{\dagger}
      +\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}+
      \boldsymbol{\tilde{J}}_{dij}^{f,+-}\,
      n_{mi}\, a_{mi}\, a_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{dij}^{f,--}\,
      a_{mi}^{\dagger}\, n_{mi}\, a_{m+d_{ij},j}
    \Bigr)
  \Biggr]
