.. math::
  {\cal H}^{Cubic}=
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
    &\left(
    -S_i^{1/2}
      \left(\boldsymbol{\tilde{J}}_{mdij}^{pf}\,\,a_{mi}\,n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{tf}\,a_{mi}^{\dagger}\,n_{m+d_{ij},j}\right)\right.
      \\&
    -S_j^{1/2}
    \left(
      \boldsymbol{\tilde{J}_{mdij}^{fp}}\,n_{mi}\,a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}_{mdij}^{ft}}\,n_{mi}\,a_{m+d_{ij},j}
     \right)
    \\&
    -\dfrac{S_j}{4\,S_i^{1/2}}
      \left(
      \boldsymbol{\tilde{J}}_{mdij}^{pf}\,n_{mi}\,a_{mi}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{tf}\,a_{mi}^\dagger\,n_{mi}
      \right)
      \\&\left.
     -\dfrac{S_i}{4\,S_j^{1/2}}
      \left(
      \boldsymbol{\tilde{J}}_{mdij}^{fp}\,a_{m+d_{ij},j}^\dagger\,n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{ft}\,n_{m+d_{ij},j}\,a_{m+d_{ij},j}
     \right)
     \right)
