.. math::
  H
  =
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d}_{ij}, i\ne j\vert_{\boldsymbol{d}_{ij}} = \boldsymbol{0}}
  \boldsymbol{S}_{mi}^{\dagger}\,
  \boldsymbol{J}_{\boldsymbol{d}ij}\,
  \boldsymbol{S}_{m+d_{ij},j}\,
  + \,\sum_{m,i}\,
  \boldsymbol{S}_{mi}^\dagger\,
  \boldsymbol{A}_i\,
  \boldsymbol{S}_{mi}\,
  +\,
  \mu_B\,\boldsymbol{h}^{\dagger}\,
  \sum_{m,i}\, g_i\, \boldsymbol{S}_{mi}
