.. math::
  {\cal H}
  =
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
  (\boldsymbol{{\cal S}_{mi}^{F,s}})^{\dagger}\,
  (\boldsymbol{R_i^s})^\dagger\,
  (\boldsymbol{R_m^s})^{\dagger}\,
  \boldsymbol{J_{ij}^s}(\boldsymbol{d_{ij}})\,
  \boldsymbol{R_{m+d_{ij}}^s}\,
  \boldsymbol{R_j^s}\,
  \boldsymbol{{\cal S}_{m+d_{ij},j}^{F,s}}
  +
  \mu_B\,\boldsymbol{h}^{\dagger}\,
  \sum_{m,i}
  \,g_i\,
  \boldsymbol{R_m}\,
  \boldsymbol{R_i}\,
  \boldsymbol{{\cal S}_{mi}^{F,s}}
