.. math::
  {\cal H}^{Biquadratic}
  &=
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
  \Biggl[
    \boldsymbol{\tilde{J}}_{mdij}^{ff}\,n_{mi}\,n_{m+d_{ij},j}
    \\&-
    \dfrac{1}{4}\, \left(\frac{S_i}{S_j}\right)^{1/2}\,
    \Bigl(
      \boldsymbol{\tilde{J}}_{mdij}^{pp}\,
      a_{mi}\, a_{m+d_{ij},j}^{\dagger}\, n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{pt}\,
      a_{mi}\, a_{m+d_{ij},j}\, n_{m+d_{ij},j}
      +\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}+
      \boldsymbol{\tilde{J}}_{mdij}^{tp}\,
      a_{mi}^{\dagger}\, a_{m+d_{ij},j}^{\dagger}\, n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{tt}\,
      a_{mi}^{\dagger}\, a_{m+d_{ij},j}\, n_{m+d_{ij},j}
    \Bigr)
    \\
    &-
    \dfrac{1}{4}\, \left(\frac{S_j}{S_i}\right)^{1/2}\,
    \Bigl(
      \boldsymbol{\tilde{J}}_{mdij}^{pp}\,
      n_{mi}\, a_{mi}\, a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{pt}\,
      n_{mi}\, a_{mi}\, a_{m+d_{ij},j}
      +\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}+
      \boldsymbol{\tilde{J}}_{mdij}^{tp}\,
      n_{mi}\, a_{mi}^{\dagger}\, a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{tt}\,
      n_{mi}\, a_{mi}^{\dagger}\, a_{m+d_{ij},j}
    \Bigr)
  \Biggr]
