.. math::
  {\cal H}^{LSWT}
  &=
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d}_{ij}, i, j}
  \Biggl[
    -\, \boldsymbol{\tilde{J}}_{mdij}^{f,00}\,
      \left(S_j\, n_{mi}\, + S_i\, n_{m+d_{ij},j}\right)
    \\&\phantom{=\dfrac{1}{2} \sum_{m, \boldsymbol{d}_{ij}, i, j}\Biggl[}+
    (S_i\,S_j)^{1/2}
    \left(
      \boldsymbol{\tilde{J}}_{mdij}^{f,++}\,
      a_{mi}\, a_{m+d_{ij},j}^\dagger
      +
      \boldsymbol{\tilde{J}}_{mdij}^{f,+-}\,
      a_{mi}\, a_{m+d_{ij},j}+
      \boldsymbol{\tilde{J}}_{mdij}^{f,-+}\,
      a_{mi}^{\dagger}\, a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{f,--}\,
      a_{mi}^\dagger\, a_{m+d_{ij},j}
    \right)
  \Biggr]
  -\\&-
  \mu_B\, ^{sf}\boldsymbol{h}^{\dagger}\,
  \sum_{m,i}\, g_i\, S_i\,
  ^{sf}\boldsymbol{R_m}\, ^{sf}\boldsymbol{\hat{f}}_i\,
  {\cal n}_{mi}
