.. math::
  {\cal H}^{Cubic}
  &=
  \dfrac{1}{2}
  \sum_{m, \boldsymbol{d_{ij}}, i, j}
  \Biggl[
    -S_i^{1/2}
    \left(
      \boldsymbol{\tilde{J}}_{mdij}^{pf}\,\,a_{mi}\,n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{tf}\,a_{mi}^{\dagger}\,n_{m+d_{ij},j}
    \right)
    -\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}-
    S_j^{1/2}
    \left(
      \boldsymbol{\tilde{J}_{mdij}^{fp}}\, n_{mi}\,a_{m+d_{ij},j}^{\dagger}
      +
      \boldsymbol{\tilde{J}_{mdij}^{ft}}\, n_{mi}\,a_{m+d_{ij},j}
    \right)
    -\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}-
    \dfrac{1}{4}\, S_i\, S_j^{-1/2}
    \left(
      \boldsymbol{\tilde{J}}_{mdij}^{fp}\, a_{m+d_{ij},j}^{\dagger}\, n_{m+d_{ij},j}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{ft}\, n_{m+d_{ij},j}\, a_{m+d_{ij},j}
    \right)
    -\\&\phantom{=\dfrac{1}{2}\sum_{m, \boldsymbol{d_{ij}}, i, j}\Biggl[}-
    \dfrac{1}{4}S_i^{-1/2}\, S_j
    \left(
      \boldsymbol{\tilde{J}}_{mdij}^{pf}\, n_{mi}\, a_{mi}
      +
      \boldsymbol{\tilde{J}}_{mdij}^{tf}\, a_{mi}^{\dagger}\, n_{mi}
    \right)
  \Biggr]
  -\\&-
  \mu_B \boldsymbol{h}^{\dagger}\,
  \sum_{m,i}\, \dfrac{g_i}{4S_i^{1/2}}\,
  \boldsymbol{R_m}\,
  \left(
    \boldsymbol{\hat{p}}_i^s
    a_{mi}^{\dagger}\, n_{mi}
    +
    \boldsymbol{\hat{t}}_i^s
    n_{mi}\, a_{mi}
  \right)
