.. math::
  \boldsymbol{R}_i^s
  =\boldsymbol{T}^\dagger\,\boldsymbol{R}_i\,\boldsymbol{T}
  =\dfrac{1}{2}
  \begin{pmatrix}
    1+\cos\theta_i                     &
    (\cos\theta_i-1)e^{-2i\phi_i}      &
    \sqrt{2}\sin\theta_i e^{-i\phi_i}  \\
    (\cos\theta_i - 1)e^{2i\phi_i}     &
    1 + \cos\theta_i                   &
    \sqrt{2}\sin\theta_i e^{i\phi_i}   \\
    -\sqrt{2}\sin\theta_i e^{i\phi_i}  &
    -\sqrt{2}\sin\theta_i e^{-i\phi_i} &
    2\cos\theta_i                      \\
  \end{pmatrix}
