.. math::
  ^n\boldsymbol{R}_i
  =\bra{\,u\,v\,n\,}\,\boldsymbol{R_i}\,\ket{\,u\,v\,n\,}
  =
  \begin{pmatrix}
    \cos\theta_i + \sin^2\phi_i\, \, (1 - \cos\theta_i) &
    -\sin\phi_i\, \cos\phi_i\, \, (1 - \cos\theta_i)    &
    \cos\phi_i\, \sin\theta_i                           \\
    -\sin\phi_i\, \cos\phi_i\, \, (1 - \cos\theta_i)    &
    \cos\theta_i + \cos^2\phi_i\, \, (1 - \cos\theta_i) &
    \sin\phi_i\, \sin\theta_i                           \\
    -\cos\phi_i\, \sin\theta_i &
    -\sin\phi_i\, \sin\theta_i &
    \cos\theta_i               \\
  \end{pmatrix}
