.. math::
  \boldsymbol{S_{mi}^s}
  =
  \begin{pmatrix}
    \dfrac{S_{mi}^{-}}{\sqrt{2}} \\
    \dfrac{S_{mi}^{+}}{\sqrt{2}} \\
    S_{mi}^{n} \\
  \end{pmatrix}
  =
  S_i
  \begin{pmatrix}
     \dfrac{\sin\theta_i}{\sqrt{2}}\, e^{- i (\boldsymbol{q} \cdot \boldsymbol{r_m} + \phi_i)} \\
     \dfrac{\sin\theta_i}{\sqrt{2}}\, e^{+ i (\boldsymbol{q} \cdot \boldsymbol{r_m} + \phi_i)} \\
     \cos\theta_i
  \end{pmatrix}
