This documentation uses three reference frames.

* The conventional cartesian frame
  ":math:`(\,x\,y\,z\,)`", that is spanned by the unit vectors
  :math:`(\,\ket{x},\,\ket{y},\, \ket{z}\,)`.

* The global rotated frame that defines the helical cone axis :math:`\boldsymbol{\hat{n}}`.
  This is denoted by ":math:`(\,u\,v\,n\,)`" and is spanned by the set of orthogonal
  unit vectors :math:`(\,\ket{u},\,\ket{v},\,\ket{n}\,)`, that are obtained by rotating
  the basis set :math:`(\,x\,y\,z\,)`.

* The local rotated reference frame defining each atomic spin :math:`\ket{S_i^0}= S_i\,\ket{f_i}`.
  This is denoted by ":math:`(\,p_i\,t_i\,f_i\,)`" and is spanned at each site :math:`i`
  by the set of orthogonal unit vectors :math:`(\,\ket{p_i},\,\ket{t_i},\,\ket{f_i}\,)`.
  These are obtained by local rotations of the basis set :math:`(\,u\,v\,n\,)`.

The terms "reference frame", "coordinate system", "basis" are fully equivalent.
