.. math::
  \boldsymbol{\tilde{S}_{m+d_{ij},j}^s}
  =&\,
  \left(\,
    \boldsymbol{p_j^s}\,
    \boldsymbol{t_j^s}\,
    \boldsymbol{f_j^s}\,
  \right)\,
  \begin{pmatrix}
   \sqrt{S_j}\, a_{m+d_{ij},j}^{\dagger}-
      \dfrac{a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}}{4\,\sqrt{S_j}}
    \\
    \sqrt{S_j}\,a_{m+d_{ij},j}-
      \dfrac{a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}\,a_{m+d_{ij},j}}{4\,\sqrt{S_j}}
    \\
    S_j - a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}
    \\
  \end{pmatrix}
  =\\=&\,
  S_j\,\boldsymbol{f_j^s}+
    \sqrt{S_j}\,
    \left(
      a_{m+d_{ij},j}^{\dagger}\,\boldsymbol{p_j^s}
      +a_{m+d_{ij},j}\,\boldsymbol{t_j}
    \right)
    -a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}\boldsymbol{f_j^s}
    -\\&-
    \dfrac{1}{4\,S_j^{1/2}}\,
    \left(
      a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}\,\boldsymbol{p_j^s}
      +a_{m+d_{ij},j}^{\dagger}\,a_{m+d_{ij},j}\,a_{m+d_{ij},j}\,\boldsymbol{t_j^s}
    \right)
  \Biggr]
