.. math::
  (\boldsymbol{\tilde{S}_{mi}^s})^{\dagger}
  =&
  \,S_i\,
  \left(
    \dfrac{1}{\sqrt{S_i}}\,
    \left[
      a_{mi}-\dfrac{a_{mi}^{\dagger}\,a_{mi}\,a_{mi}}{4S_i}
    \right],\,
    \dfrac{1}{\sqrt{S_i}}\,
    \left[
      a_{mi}^{\dagger}-\dfrac{a_{mi}^{\dagger}\,a_{mi}^{\dagger}\,a_{mi}}{4S_i}
    \right],\,
    1 - \dfrac{a_{mi}^{\dagger}\,a_{mi}}{S_i}
  \right)
  \begin{pmatrix}
    (\boldsymbol{p_i^s})^\dagger \\
    (\boldsymbol{t_i^s})^\dagger \\
    (\boldsymbol{f_i^s})^\dagger \\
  \end{pmatrix}
  =\\&=
  S_i
  \Biggl[\,
    (\boldsymbol{f_i^s})^\dagger+
    \dfrac{1}{\sqrt{S_i}}\,
    \left(
      a_{mi}\,(\boldsymbol{p_i^s})^\dagger
      +a_{mi}^{\dagger}\,(\boldsymbol{t_i^s})^\dagger
    \right)
    -\dfrac{1}{S_i}\,a_{mi}^{\dagger}\,a_{mi}\,(\boldsymbol{f_i^s})^\dagger
    -\\&-
    \dfrac{1}{4S_i^{3/2}}\,
    \left(
      a_{mi}^{\dagger}\,a_{mi}\,a_{mi}\,(\boldsymbol{p_i^s})^\dagger
      +a_{mi}^{\dagger}\,a_{mi}^{\dagger}\,a_{mi}\,(\boldsymbol{t_i^s})^\dagger
    \right)
  \Biggr]
