.. math::
  (\boldsymbol{\tilde{S}_{mi}^s})^{\dagger}
  =&
  \left(
    \sqrt{S_i}\,
      a_{mi}-\dfrac{a_{mi}^{\dagger}\,a_{mi}\,a_{mi}}{4\,\sqrt{S_i}}
      ,\,
      \sqrt{S_i}\,
      a_{mi}^{\dagger}-\dfrac{a_{mi}^{\dagger}\,a_{mi}^{\dagger}\,a_{mi}}{4\,\sqrt{S_i}},\,
    S_i - a_{mi}^{\dagger}\,a_{mi}
  \right)
  \begin{pmatrix}
    (\boldsymbol{p_i^s})^\dagger \\
    (\boldsymbol{t_i^s})^\dagger \\
    (\boldsymbol{f_i^s})^\dagger \\
  \end{pmatrix}
  =\\&=
  S_i\,
    (\boldsymbol{f_i^s})^\dagger+
    \sqrt{S_i}\,
    \left(
      a_{mi}\,(\boldsymbol{p_i^s})^\dagger
      +a_{mi}^{\dagger}\,(\boldsymbol{t_i^s})^\dagger
    \right)
    -a_{mi}^{\dagger}\,a_{mi}\,(\boldsymbol{f_i^s})^\dagger
    -\\&-
    \dfrac{1}{4S_i^{1/2}}\,
    \left(
      a_{mi}^{\dagger}\,a_{mi}\,a_{mi}\,(\boldsymbol{p_i^s})^\dagger
      +a_{mi}^{\dagger}\,a_{mi}^{\dagger}\,a_{mi}\,(\boldsymbol{t_i^s})^\dagger
    \right)
  \Biggr]
