.. math::
  (\boldsymbol{S_i^{F,s}})^{\dagger}
  (\boldsymbol{R_i^s})^{\dagger}
  =
  (0,0,S_i)
  \begin{pmatrix}
    \dfrac{1+\cos\theta_i}{2}                     &
    \dfrac{(\cos\theta_i - 1)e^{-2i\phi_i}}{2}    &
    \dfrac{-\sin\theta_i e^{-i\phi_i} }{\sqrt{2}} \\
    \dfrac{(\cos\theta_i-1)e^{2i\phi_i}}{2}       &
    \dfrac{1 + \cos\theta_i}{2}                   &
    \dfrac{-\sin\theta_i e^{i\phi_i}}{\sqrt{2}}   \\
    \dfrac{\sin\theta_i e^{i\phi_i}}{\sqrt{2}}    &
    \dfrac{\sin\theta_i e^{-i\phi_i}}{\sqrt{2}}   &
    \cos\theta_i                                  \\
  \end{pmatrix}
  =
  S_i
  \left(
    \dfrac{\sin\theta_i e^{i\phi_i}}{\sqrt{2}}  ,
    \dfrac{\sin\theta_i e^{-i\phi_i}}{\sqrt{2}} ,
    \cos\theta_i
  \right)
